Add lower bound on obuilder-spec
This should fix the ci failure
https://ocaml.ci.dev/github/ocurrent/opam-repo-ci/commit/7148fc6d34348df255f8f6f57e0d97d826f6ed57/variant/%28lower-bound%29#L1034-1034

```
File "opam-ci-check/lib/opam_build.mli", line 12, characters 2-17:
12 |   Obuilder_spec.t
^^^^^^^^^^^^^^^
Error: Unbound type constructor Obuilder_spec.t
```

Resulting from the fact that `Obuilder_spec.t` was not introduced until
version 0.2.